### PR TITLE
A few small suggestions that jumped out at me

### PR DESCRIPTION
**Pull request by Ricyteach**
I'll look at the later parts of the tutorial more closely later. These were small points of confusion for me upon first reading. The actual discussion/explanation of how the library works is quite understandable and does a good job illustrating how to use it.

### CODE REVIEW

**Comment by bskinn** [comment]
I like what you were trying to do here with highlighting the tokens more... the specific format you used doesn't [render so well](https://pent.readthedocs.io/en/pr94-doc/tutorial/basics/tokens.html), though, at least to my eye.

I'll figure something out, to punch it up some more. Maybe a larger & bold font for the token, or something.

**Comment by Ricyteach** [comment]
Yup, looks awful. Didn't know how that would turn out.

**Comment by bskinn** [comment]
If you signed up for ReadTheDocs, you might be able to enable `pent` there and it would just build the docset, since you're working on `master` in your fork.

Was easy enough to merge your changes into a new branch in my repo, though.

**Comment by bskinn** [comment]
@Ricyteach What if I left it ~as-is, but changed the formatting on the token characters themselves?

E.g., 

image

**Comment by Ricyteach** [comment]
> image

That is a HUGE improvement.

**Comment by bskinn** [comment]
Revisions made in #96.

**Pull request closed without merging**
